#!/usr/bin/env bash

CC=${CC:-}

GCC_BIN=${GCC_BIN:-$(command -v gcc 2>/dev/null)}
CLANG_BIN=${CLANG_BIN:-$(command -v clang 2>/dev/null)}

RE2C_BIN=${RE2C_BIN:-$(command -v re2c 2>/dev/null)}

rm -f *.o *.lo

if [ x"$CC" != x ]; then
    if [ x"$GCC_BIN" != x ]; then
        export CC="gcc"
    else
        if [ x"$CLANG_BIN" != x ]; then
            export CC="clang"
        fi
    fi
fi

if [ x"$CC" = x ]; then
    echo -e "error: unable to locate the compiler"
    exit 1
fi

if [ x"$RE2C_BIN" = x ]; then
  echo -e "error: unable to locate the re2c"
  exit 2
fi

${RE2C_BIN} -o scanner.c scanner.re

# Compile lemon
if [ ! -f lemon ]; then
    ${CC} lemon.c -o lemon
fi

echo -e "Generating PHP 5 parser..."
./lemon -s parser.php5.lemon
if [ ! -f parser.php5.c ]; then
    echo "error: couldn't generate parser"
    exit 2
fi
echo

echo -e "Generating PHP 7 parser..."
./lemon -s parser.php7.lemon
if [ ! -f parser.php7.c ]; then
    echo "error: couldn't generate parser"
    exit 2
fi
echo
